version: '3.8'

services:
  dou-blockchain:
    build: .
    volumes:
      - ./data:/app/data
    environment:
      - PYTHONPATH=/app/src
    command: create  # Default command, can be overridden

  # Optional: Add a database service in future
  # database:
  #   image: postgres:13
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

volumes:
  # postgres_data:  # Uncomment when adding database
  dou_blockchain_data:
    driver: local
